# Generated by Django 6.1.1 on 2026-10-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('menuitem', 'order')},
        ),
    ]
